/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package u0.movieratings;

import java.util.Map;
import java.io.IOException;
import java.util.List; 

public class App {
    public String getGreeting() {
        return "Welcome To Movie Ratings";
    }
 
    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
        RatingReader reader = new RatingReader("movie-ratings-test.csv");
        List<Rating> rating = reader.getAllRatings();
        for(Rating value : rating){
            System.out.println("Movie Name: " + value.getMovieName());
            System.out.println("Movie Rater: " + value.getRaterName());
            System.out.println("Movie Rating: " + value.getRating());
        }
        
        //averageRatings(rating);
    }

    //public static List<Rating> averageRatings(Map <String, Integer> myMap){
        //TODO Get average ratings
    //}

}
